trigger:
  branches:
    include:
      - master
      - releases/*

variables:
  node_version: 12.x
  benchmark_type: $(benchmark.type)
  benchmark_launches: $(benchmark.launches)
  benchmark_max_stdev: $(benchmark.max_stdev)
  benchmark_retries: $(benchmark.retries)
  benchmark_options: $(benchmark.options)

jobs:
  - job: Benchmark
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: steps-build.yml
        parameters:
          node_version: $(node_version)
      - template: steps-benchmark.yml
        parameters:
          node_version: $(node_version)
          benchmark_type: $(benchmark_type)
          benchmark_launches: $(benchmark_launches)
          benchmark_max_stdev: $(benchmark_max_stdev)
          benchmark_retries: $(benchmark_retries)
          benchmark_options: $(benchmark_options)
